[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=0
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=Install BiomedPPTX - Biomedical PowerPoint Extensions?
DisplayLicense=
FinishMessage=BiomedPPTX installation complete!
TargetName=C:\Users\Eleonora Ocampo\Documents\__Scratch\BiomedPPTX-Installer\BiomedPPTX-Setup.exe
FriendlyName=BiomedPPTX Installer
AppLaunched=BiomedPPTXInstaller.exe
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
SourceFiles=SourceFiles
[Strings]
FILE0="BiomedPPTXInstaller.exe"
FILE1="data.zip"
FILE2="smart-assets.zip"
FILE3="bioart_index.json"
FILE4="Tutorial.pptx"
[SourceFiles]
SourceFiles0=C:\Users\Eleonora Ocampo\Documents\__Scratch\BiomedPPTX-Installer\Release\
[SourceFiles0]
%FILE0%=
%FILE1%=
%FILE2%=
%FILE3%=
%FILE4%=